// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MySql.Data.MySqlClient;
using UIKit;

namespace YeahFit
{
    public partial class AwardsViewController : UIViewController
    {
        public static MySqlConnection con = new MySqlConnection(@"Server=localhost;Database=YeahFit;User Id=root;Password=; CharSet = utf8");

        public AwardsViewController(IntPtr handle) : base(handle)
        {
        }

        /// <summary>
        /// Initialize
        /// </summary>
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        /// <summary>
        /// View reappears
        /// </summary>
        /// <param name="animated"></param>
        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);

            Alert();

            if (LoginViewController.loggedin == true)
            {
                con = new MySqlConnection(@"Server=localhost;Database=YeahFit;User Id=root;Password=; CharSet = utf8");
                con.Open();

                MySqlCommand initialize = new MySqlCommand($"SELECT * From Benutzer_Awards WHERE BenutzerID = {LoginViewController.userID}", con);

                using (MySqlDataReader reader = initialize.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        lbl_PerfectWeekCounter.Text = Convert.ToString(reader["Perfekte Woche"]);
                        lbl_PerfectMonthCounter.Text = Convert.ToString(reader["Perfekter Monat"]);
                        lbl_PerfectYearCounter.Text = Convert.ToString(reader["Perfektes Jahr"]);
                        lbl_ChallengeCounter.Text = Convert.ToString(reader["Starte eine Challenge"]);
                        lbl_AdvancedMidWorkoutCounter.Text = Convert.ToString(reader["Absolviere ein mittleres Workout"]);
                        lbl_HardWorkoutCounter.Text = Convert.ToString(reader["Absolviere ein hartes Workout"]);
                    }
                }
            }
        }

        /// <summary>
        /// Reload FirstView if user swipes down the View
        /// + Set edit in SecondView false
        /// </summary>
        /// <param name="animated"></param>
        public override void ViewDidDisappear(bool animated)
        {
            base.ViewDidDisappear(animated);


        }

        void Alert()
        {
            if (LoginViewController.loggedin == false)
            {
                //Create Alert
                var okAlertController = UIAlertController.Create("Melde dich an", "Melde dich an, um Awards freischalten und sammeln zu können.", UIAlertControllerStyle.Alert);

                //Add Action
                okAlertController.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));

                // Present Alert
                PresentViewController(okAlertController, true, null);
            }
        }
    }
}