// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using MySql.Data.MySqlClient;
using UIKit;
using System.Drawing;

namespace YeahFit
{
	public partial class ChallengeOverviewViewController : UIViewController
	{
        public UINavigationController CurrentNavigationController;

        // Main list of all recipes
        public static List<Challenge> challenges;
        //public static List<Workout> workouts;


        public ChallengeOverviewViewController(IntPtr handle) : base(handle)
        {
        }


        /// <summary>
        /// Initialization of the main view 'FirstView'
        /// </summary>
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            // Perform any additional setup after loading the view, typically from a nib.

            Filter2ViewController.challengeOverviewViewController = this;
            
            // Loading the tableView
            ChallengeViewController.firstViewController = this;
            WorkoutViewController.secondViewController = this;
            challenges = null;
            //workouts = null;

            // Get data from database
            InitializeChallenges.Initialize();
            InitializeWorkouts.Initialize();

            // Setting recipes as its source
            tableView_ChallengeOverview.Source = new ChallengeTableViewSource(challenges, this, CurrentNavigationController);
            tableView_ChallengeOverview.RowHeight = 195;

            // Reload tableView
            tableView_ChallengeOverview.ReloadData();

        }

        /// <summary>
        /// Reload tabeView_Recipes after view reappeared
        /// </summary>
        /// <param name="animated"></param>
        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);
            Filter2ViewController.challengeOverviewViewController = this;
            ChallengeViewController.firstViewController = this;
            challenges = null;
            InitializeChallenges.Initialize();
            tableView_ChallengeOverview.Source = new ChallengeTableViewSource(challenges, this, CurrentNavigationController);
            tableView_ChallengeOverview.RowHeight = 195;
            tableView_ChallengeOverview.ReloadData();
        }

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();
            // Release any cached data, images, etc that aren't in use.
        }

        /// <summary>
        /// Reload tabeView_Recipes from other Views
        /// </summary>
        /// <param name="firstViewController"></param>
        public static void Refresh(ChallengeOverviewViewController firstViewController)
        {
            firstViewController.ViewDidAppear(true);
        }
    }
}
