// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace YeahFit
{
    public partial class FilterViewController : UIViewController
    {
        static string filter;
        static string difficulty;
        static bool favourite;

        public static WorkoutOverviewViewController workoutOverviewViewController;

        public FilterViewController(IntPtr handle) : base(handle)
        {
        }

        /// <summary>
        /// Initialize
        /// </summary>
        public override void ViewDidLoad()
        {
            // Initialize favourite button
            if (favourite == true)
            {
                SelectButtonColor.SelectButton(btn_FilterFavourite, true);
            }

            // Initialize last added button
            if (filter == "LastAdded" || filter == null)
            {
                filter = "LastAdded";

                SelectButtonColor.SelectButton(Filter_LastAdded, true);
                SelectButtonColor.SelectButton(Filter_FirstAdded, false);
                SelectButtonColor.SelectButton(btn_FilterAlphAsc, false);
                SelectButtonColor.SelectButton(btn_FilterAlphDesc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationAsc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationDesc, false);
            }

            // Initialize firt added button
            else if (filter == "FirstAdded")
            {
                SelectButtonColor.SelectButton(Filter_LastAdded, false);
                SelectButtonColor.SelectButton(Filter_FirstAdded, true);
                SelectButtonColor.SelectButton(btn_FilterAlphAsc, false);
                SelectButtonColor.SelectButton(btn_FilterAlphDesc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationAsc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationDesc, false);
            }

            // Initialize alphabetical ascending button
            if (filter == "AlphAsc")
            {
                SelectButtonColor.SelectButton(Filter_LastAdded, false);
                SelectButtonColor.SelectButton(Filter_FirstAdded, false);
                SelectButtonColor.SelectButton(btn_FilterAlphAsc, true);
                SelectButtonColor.SelectButton(btn_FilterAlphDesc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationAsc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationDesc, false);
            }

            // Initialize alphabetical descending button
            else if (filter == "AlphDesc")
            {
                SelectButtonColor.SelectButton(Filter_LastAdded, false);
                SelectButtonColor.SelectButton(Filter_FirstAdded, false);
                SelectButtonColor.SelectButton(btn_FilterAlphAsc, false);
                SelectButtonColor.SelectButton(btn_FilterAlphDesc, true);
                SelectButtonColor.SelectButton(btn_FilterDurationAsc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationDesc, false);
            }

            // Initialize duration ascending button
            if (filter == "DurationAsc")
            {
                SelectButtonColor.SelectButton(Filter_LastAdded, false);
                SelectButtonColor.SelectButton(Filter_FirstAdded, false);
                SelectButtonColor.SelectButton(btn_FilterAlphAsc, false);
                SelectButtonColor.SelectButton(btn_FilterAlphDesc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationAsc, true);
                SelectButtonColor.SelectButton(btn_FilterDurationDesc, false);
            }

            // Initialize duration descending button
            else if (filter == "DurationDesc")
            {
                SelectButtonColor.SelectButton(Filter_LastAdded, false);
                SelectButtonColor.SelectButton(Filter_FirstAdded, false);
                SelectButtonColor.SelectButton(btn_FilterAlphAsc, false);
                SelectButtonColor.SelectButton(btn_FilterAlphDesc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationAsc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationDesc, true);
            }

            // Initialize difficulty buttons
            if (difficulty == "Beginner")
            {
                SelectButtonColor.SelectButton(btn_FilterDifficultyEasy, true);
                SelectButtonColor.SelectButton(btn_FilterDifficultyAdvanced, false);
                SelectButtonColor.SelectButton(btn_FilterDifficultyHard, false);
            }
            else if (difficulty == "Fortgeschritten")
            {
                SelectButtonColor.SelectButton(btn_FilterDifficultyEasy, false);
                SelectButtonColor.SelectButton(btn_FilterDifficultyAdvanced, true);
                SelectButtonColor.SelectButton(btn_FilterDifficultyHard, false);
            }
            else if (difficulty == "Hart")
            {
                SelectButtonColor.SelectButton(btn_FilterDifficultyEasy, false);
                SelectButtonColor.SelectButton(btn_FilterDifficultyAdvanced, false);
                SelectButtonColor.SelectButton(btn_FilterDifficultyHard, true);
            }

            // Favourite button click
            btn_FilterFavourite.TouchUpInside += (sender, e) =>
            {
                if (favourite == false)
                {
                    favourite = true;
                    SelectButtonColor.SelectButton(btn_FilterFavourite, true);
                }
                else
                {
                    favourite = false;
                    SelectButtonColor.SelectButton(btn_FilterFavourite, false);
                }
            };

            // Last added button click
            Filter_LastAdded.TouchUpInside += (sender, e) =>
            {
                filter = "LastAdded";

                SelectButtonColor.SelectButton(Filter_LastAdded, true);
                SelectButtonColor.SelectButton(Filter_FirstAdded, false);
                SelectButtonColor.SelectButton(btn_FilterAlphAsc, false);
                SelectButtonColor.SelectButton(btn_FilterAlphDesc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationAsc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationDesc, false);
            };

            // First added button click
            Filter_FirstAdded.TouchUpInside += (sender, e) =>
            {
                filter = "FirstAdded";

                SelectButtonColor.SelectButton(Filter_LastAdded, false);
                SelectButtonColor.SelectButton(Filter_FirstAdded, true);
                SelectButtonColor.SelectButton(btn_FilterAlphAsc, false);
                SelectButtonColor.SelectButton(btn_FilterAlphDesc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationAsc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationDesc, false);
            };

            // Alphabetical ascending button click
            btn_FilterAlphAsc.TouchUpInside += (sender, e) =>
            {
                filter = "AlphAsc";

                SelectButtonColor.SelectButton(Filter_LastAdded, false);
                SelectButtonColor.SelectButton(Filter_FirstAdded, false);
                SelectButtonColor.SelectButton(btn_FilterAlphAsc, true);
                SelectButtonColor.SelectButton(btn_FilterAlphDesc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationAsc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationDesc, false);
            };

            // Alphabetical descending button click
            btn_FilterAlphDesc.TouchUpInside += (sender, e) =>
            {
                filter = "AlphDesc";

                SelectButtonColor.SelectButton(Filter_LastAdded, false);
                SelectButtonColor.SelectButton(Filter_FirstAdded, false);
                SelectButtonColor.SelectButton(btn_FilterAlphAsc, false);
                SelectButtonColor.SelectButton(btn_FilterAlphDesc, true);
                SelectButtonColor.SelectButton(btn_FilterDurationAsc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationDesc, false);
            };

            // Duration ascending button click
            btn_FilterDurationAsc.TouchUpInside += (sender, e) =>
            {
                filter = "DurationAsc";

                SelectButtonColor.SelectButton(Filter_LastAdded, false);
                SelectButtonColor.SelectButton(Filter_FirstAdded, false);
                SelectButtonColor.SelectButton(btn_FilterAlphAsc, false);
                SelectButtonColor.SelectButton(btn_FilterAlphDesc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationAsc, true);
                SelectButtonColor.SelectButton(btn_FilterDurationDesc, false);
            };

            // Duration descending button click
            btn_FilterDurationDesc.TouchUpInside += (sender, e) =>
            {
                filter = "DurationDesc";

                SelectButtonColor.SelectButton(Filter_LastAdded, false);
                SelectButtonColor.SelectButton(Filter_FirstAdded, false);
                SelectButtonColor.SelectButton(btn_FilterAlphAsc, false);
                SelectButtonColor.SelectButton(btn_FilterAlphDesc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationAsc, false);
                SelectButtonColor.SelectButton(btn_FilterDurationDesc, true);
            };

            // Difficulty beginner button click
            btn_FilterDifficultyEasy.TouchUpInside += (sender, e) =>
            {
                // If user taps on button again, it'll get deselected
                if (difficulty != "Beginner")
                {
                    difficulty = "Beginner";
                    SelectButtonColor.SelectButton(btn_FilterDifficultyEasy, true);
                }
                else
                {
                    difficulty = "";
                    SelectButtonColor.SelectButton(btn_FilterDifficultyEasy, false);
                }
                SelectButtonColor.SelectButton(btn_FilterDifficultyAdvanced, false);
                SelectButtonColor.SelectButton(btn_FilterDifficultyHard, false);
            };

            // Difficulty advanced button click
            btn_FilterDifficultyAdvanced.TouchUpInside += (sender, e) =>
            {

                // If user taps on button again, it'll get deselected
                if (difficulty != "Fortgeschritten")
                {
                    difficulty = "Fortgeschritten";
                    SelectButtonColor.SelectButton(btn_FilterDifficultyAdvanced, true);
                }
                else
                {
                    difficulty = "";
                    SelectButtonColor.SelectButton(btn_FilterDifficultyAdvanced, false);
                }
                SelectButtonColor.SelectButton(btn_FilterDifficultyEasy, false);
                SelectButtonColor.SelectButton(btn_FilterDifficultyHard, false);
            };

            // Difficulty professional button click
            btn_FilterDifficultyHard.TouchUpInside += (sender, e) =>
            {

                // If user taps on button again, it'll get deselected
                if (difficulty != "Hart")
                {
                    difficulty = "Hart";
                    SelectButtonColor.SelectButton(btn_FilterDifficultyHard, true);
                }
                else
                {
                    difficulty = "";
                    SelectButtonColor.SelectButton(btn_FilterDifficultyHard, false);
                }
                SelectButtonColor.SelectButton(btn_FilterDifficultyEasy, false);
                SelectButtonColor.SelectButton(btn_FilterDifficultyAdvanced, false);
            };

            // Filter confirm button click
            // Set filters in InitializeRecipes.cs
            btn_FilterConfirm.TouchUpInside += (sender, e) =>
            {
                InitializeWorkouts.favourite = false;
                InitializeWorkouts.order = "LastAdded";
                InitializeWorkouts.difficulty = "";

                // Set filters in InitializeRecipes.cs
                if (favourite == true)
                {
                    InitializeWorkouts.favourite = true;
                }
                if (filter == "LastAdded")
                {
                    InitializeWorkouts.order = "LastAdded";
                }
                else if (filter == "FirstAdded")
                {
                    InitializeWorkouts.order = "FirstAdded";
                }
                else if (filter == "AlphAsc")
                {
                    InitializeWorkouts.order = "AlphAsc";
                }
                else if (filter == "AlphDesc")
                {
                    InitializeWorkouts.order = "AlphDesc";
                }
                else if (filter == "DurationAsc")
                {
                    InitializeWorkouts.order = "DurationAsc";
                }
                else if (filter == "DurationDesc")
                {
                    InitializeWorkouts.order = "DurationDesc";
                }
                if (difficulty == "Beginner")
                {
                    InitializeWorkouts.difficulty = "beginner";
                }
                else if (difficulty == "Fortgeschritten")
                {
                    InitializeWorkouts.difficulty = "advanced";
                }
                else if (difficulty == "Hart")
                {
                    InitializeWorkouts.difficulty = "hard";
                }

                // Set seachbar text
                InitializeWorkouts.search = searchBar_Filter.Text;


                // Go back to FirstView
                this.DismissViewController(true, () => { WorkoutOverviewViewController.Refresh(workoutOverviewViewController); });
            };
        }
            

            /// <summary>
            /// Reload TableView on FirstView if user swipes the View away
            /// </summary>
            /// <param name="animated"></param>
        public override void ViewDidDisappear(bool animated)
        {
            base.ViewDidDisappear(animated);
            this.DismissViewController(true, () => { WorkoutOverviewViewController.Refresh(workoutOverviewViewController); });
        }

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();
            // Release any cached data, images, etc that aren't in use.
        }
    
    }
}
