// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace YeahFit
{
	public partial class Filter2ViewController : UIViewController
	{
		public Filter2ViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
