// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace YeahFit
{
	public partial class LastWorkoutsViewController : UIViewController
	{
        public UINavigationController CurrentNavigationController;

        static UITableView tableView;
        public static List<Workout> internalWorkouts;

		public LastWorkoutsViewController (IntPtr handle) : base (handle)
		{
		}


        /// <summary>
        /// Initialize
        /// </summary>
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            WorkoutViewController.lastWorkouts = true;
            InitializeWorkouts.Initialize();
            // Set source for ingredient tableView
            lastWorkoutsTableView.Source = new LastWorkoutsTableViewSource(internalWorkouts, this, CurrentNavigationController);
            lastWorkoutsTableView.RowHeight = 71;

            // Reload ingredient tableView
            lastWorkoutsTableView.ReloadData();
        }

        /// <summary>
        /// View reappears
        /// </summary>
        /// <param name="animated"></param>
        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);

            Alert();

            WorkoutViewController.lastWorkouts = true;

            // Set source for ingredient tableView
            lastWorkoutsTableView.Source = new LastWorkoutsTableViewSource(internalWorkouts, this, CurrentNavigationController);
            lastWorkoutsTableView.RowHeight = 71;

            // Reload ingredient tableView
            lastWorkoutsTableView.ReloadData();
        }

        /// <summary>
        /// Reload FirstView if user swipes down the View
        /// + Set edit in SecondView false
        /// </summary>
        /// <param name="animated"></param>
        public override void ViewDidDisappear(bool animated)
        {
            base.ViewDidDisappear(animated);


        }

        void Alert()
        {
            if (LoginViewController.loggedin == false)
            {
                //Create Alert
                var okAlertController = UIAlertController.Create("Melde dich an", "Melde dich an, um deine ausgeführten Workouts zu tracken.", UIAlertControllerStyle.Alert);

                //Add Action
                okAlertController.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));

                // Present Alert
                PresentViewController(okAlertController, true, null);
            }
        }
    }
}
