// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace YeahFit
{
	public partial class LastWorkoutsViewController : UIViewController
	{
        public UINavigationController CurrentNavigationController;

        static UITableView tableView;
        public static List<Workout> workouts = new List<Workout>();
        public static List<LastWorkout> lastWorkouts = new List<LastWorkout>();
        public static List<Workout> internalWorkouts = new List<Workout>();

        public LastWorkoutsViewController (IntPtr handle) : base (handle)
		{
		}


        /// <summary>
        /// Initialize
        /// </summary>
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            if (LoginViewController.loggedin == true)
            {
                internalWorkouts = new List<Workout>();
                WorkoutViewController.lastWorkouts = true;
                InitializeWorkouts.userid = $" AND Workout.WorkoutID = (" +
                    $"SELECT Workout.WorkoutID " +
                    $"FROM Workout, Benutzer_Workout_Woche " +
                    $"WHERE Workout.WorkoutID = Benutzer_Workout_Woche.WorkoutID " +
                    $"AND Benutzer_Workout_Woche.BenutzerID='{LoginViewController.userID}'";
                InitializeWorkouts.Initialize();

                for (int i = 0; i < workouts.Count; i++)
                {
                    //if (workouts[i].id == LoginViewController.userID)
                    //{
                        internalWorkouts.Add(workouts[i]);
                    //}
                }

                // Set source for ingredient tableView
                lastWorkoutsTableView.Source = new LastWorkoutsTableViewSource(internalWorkouts, this, CurrentNavigationController);
                lastWorkoutsTableView.RowHeight = 71;

                // Reload ingredient tableView
                lastWorkoutsTableView.ReloadData();

                InitializeWorkouts.filter = "";
            }
        }

        /// <summary>
        /// View reappears
        /// </summary>
        /// <param name="animated"></param>
        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);

            Alert();

            if (LoginViewController.loggedin == true)
            {
                internalWorkouts = new List<Workout>();
                WorkoutViewController.lastWorkouts = true;

                InitializeWorkouts.userid = $" AND Workout.WorkoutID = (" +
                    $"SELECT Workout.WorkoutID " +
                    $"FROM Workout, Benutzer_Workout_Woche " +
                    $"WHERE Workout.WorkoutID = Benutzer_Workout_Woche.WorkoutID " +
                    $"AND Benutzer_Workout_Woche.BenutzerID='{LoginViewController.userID}'";
                InitializeWorkouts.Initialize();

                for (int i = 0; i < workouts.Count; i++)
                {
                    //if (workouts[i].id == LoginViewController.userID)
                    //{
                        internalWorkouts.Add(workouts[i]);
                    //}
                }




                // Set source for ingredient tableView
                lastWorkoutsTableView.Source = new LastWorkoutsTableViewSource(internalWorkouts, this, CurrentNavigationController);
                lastWorkoutsTableView.RowHeight = 71;

                // Reload ingredient tableView
                lastWorkoutsTableView.ReloadData();
                InitializeWorkouts.filter = "";
            }
        }

        /// <summary>
        /// Reload FirstView if user swipes down the View
        /// + Set edit in SecondView false
        /// </summary>
        /// <param name="animated"></param>
        public override void ViewDidDisappear(bool animated)
        {
            base.ViewDidDisappear(animated);


        }

        void Alert()
        {
            if (LoginViewController.loggedin == false)
            {
                //Create Alert
                var okAlertController = UIAlertController.Create("Melde dich an", "Melde dich an, um deine zuletzt ausgeführten Workouts zu sehen.", UIAlertControllerStyle.Alert);

                //Add Action
                okAlertController.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));

                // Present Alert
                PresentViewController(okAlertController, true, null);
            }
        }
    }
}
