// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace YeahFit
{
	public partial class UIImageViewWorkout : UIImageView
	{
		public UIImageViewWorkout (IntPtr handle) : base (handle)
		{
		}
	}
}
