// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace YeahFit
{
	public partial class UITableViewAddIngredientCell : UITableViewCell
	{
		public UITableViewAddIngredientCell (IntPtr handle) : base (handle)
		{
		}
	}
}
