// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace YeahFit
{
	public partial class UITableViewChallengeCell : UITableViewCell
	{
        bool liked;

        /// <summary>
        /// Custom cell in the FirtView for the individual recipes
        /// </summary>
        /// <param name="handle"></param>
        public UITableViewChallengeCell(IntPtr handle) : base(handle)
        {
        }

        /// <summary>
        /// Update each cell content
        /// </summary>
        /// <param name="selectedRecipe"></param>
        /// <param name="indexPath"></param>
        internal void UpdateCell(Challenge selectedChallenge, int indexPath)
        {
            // Set recipe text
            imageView_ChallengeOverview.Image = UIImage.GetSystemImage("heart.fill");
            lbl_ChallengeName.Text = selectedChallenge.ChallengeName;
            lbl_ChallengeDaysPerWeek.Text = "";

            //
            // Difficulties
            //

            // Difficulty beginner
            if (selectedChallenge.difficulty == "Beginner")
            {
                // Set difficulty text
                lbl_ChallengeDaysPerWeek.Text = lbl_ChallengeDaysPerWeek.Text + selectedChallenge.daysPerWeek + " Tage pro Woche, Anfänger";
            }

            // Difficulty advanced
            else if (selectedChallenge.difficulty == "Fortgeschritten")
            {
                // Set difficulty text
                lbl_ChallengeDaysPerWeek.Text = lbl_ChallengeDaysPerWeek.Text + selectedChallenge.daysPerWeek + " Tage pro Woche, Fortgeschritten";
            }

            // Difficulty professional
            else if (selectedChallenge.difficulty == "Hart")
            {
                // Set difficulty text
                lbl_ChallengeDaysPerWeek.Text = lbl_ChallengeDaysPerWeek.Text + selectedChallenge.daysPerWeek + " Tage pro Woche, Profi";
            }


            //
            // Liked
            //

            // Set liked
            liked = selectedChallenge.liked;
            if (liked == false)
            {
                liked = false;

                // Set image View with the normal heart
                imageView_LikeChallenge.Image = UIImage.GetSystemImage("heart");
            }
            else if (liked == true)
            {
                // Set image View with the filled heart
                imageView_LikeChallenge.Image = UIImage.GetSystemImage("heart.fill");
            }


            //
            // Recipe image
            //

            // Get recipe image from byte array
            var data = NSData.FromArray(selectedChallenge.ChallengeImage);

            // Convert to UIImage
            UIImage image = UIImage.LoadFromData(data);

            // Set as image
            imageView_ChallengeOverview.Image = image;

            // AspectFill
            imageView_ChallengeOverview.ContentMode = UIViewContentMode.ScaleAspectFill;

        }
    }
}
