// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace YeahFit
{
	public partial class UITableViewExerciseCell : UITableViewCell
	{
		public UITableViewExerciseCell (IntPtr handle) : base (handle)
		{
		}

        /// <summary>
        /// Update each cell content
        /// </summary>
        /// <param name="selectedIngredient"></param>
        /// <param name="indexPath"></param>
        internal void UpdateCell(Exercise selectedExercise, int indexPath)
        {
            // Set ingredient text
            lbl_ExerciseName.Text = selectedExercise.ExerciseName;
            lbl_SetsTimes.Text = selectedExercise.ExerciseSets + "x" + selectedExercise.ExerciseReps;

            //
            // Recipe image
            //

            // Get recipe image from byte array
            var data = NSData.FromArray(selectedExercise.ExerciseImage);

            // Convert to UIImage
            UIImage image = UIImage.LoadFromData(data);

            // Set as image
            imageView_ExerciseGif.Image = image;

            // AspectFill
            imageView_ExerciseGif.ContentMode = UIViewContentMode.ScaleAspectFill;
        }
    }
}
