// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace YeahFit
{
	public partial class UITableViewAddWorkoutCell : UITableViewCell
	{
		public UITableViewAddWorkoutCell (IntPtr handle) : base (handle)
		{
		}

        /// <summary>
        /// Update each cell content
        /// </summary>
        /// <param name="selectedStep"></param>
        /// <param name="indexPath"></param>
        internal void UpdateCell(Exercise selectedExercise, int indexPath)
        {
            // Set Preview
            if (selectedExercise != null)
            {
                if (selectedExercise.ExerciseName != "")
                {
                    lbl_ExerciseName.Text = selectedExercise.ExerciseName;
                    lbl_SetsReps.Text = selectedExercise.ExerciseSets + "x" + selectedExercise.ExerciseReps;
                    //
                    // Recipe image
                    //

                    // Get recipe image from byte array
                    var data = NSData.FromArray(selectedExercise.ExerciseImage);

                    // Convert to UIImage
                    UIImage image = UIImage.LoadFromData(data);

                    // Set as image
                    imageView_Exercise.Image = image;

                    // AspectFill
                    imageView_Exercise.ContentMode = UIViewContentMode.ScaleAspectFill;
                }
            }
        }
    }
}
