// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace YeahFit
{
	public partial class UITableViewChallengeWorkoutCell : UITableViewCell
	{
		public UITableViewChallengeWorkoutCell (IntPtr handle) : base (handle)
		{
		}

        /// <summary>
        /// Update each cell content
        /// </summary>
        /// <param name="selectedRecipe"></param>
        /// <param name="indexPath"></param>
        internal void UpdateCell(Workout selectedWorkout, int indexPath)
        {
            // Set recipe text
            lbl_WorkoutName.Text = selectedWorkout.WorkoutName;
            lbl_categoryDifficulty.Text = "";


            //
            // Categories
            //

            // Category: Breakfast
            if (selectedWorkout.core == true)
            {
                // If there were categories set before
                if (lbl_categoryDifficulty.Text != "")
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = lbl_categoryDifficulty.Text + ", Core";
                }
                else
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = "Core";
                }
            }

            // Category: Lunch
            if (selectedWorkout.upperBody == true)
            {
                // If there were categories set before
                if (lbl_categoryDifficulty.Text != "")
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = lbl_categoryDifficulty.Text + ", Oberkörper";
                }
                else
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = "Oberkörper";
                }
            }

            // Category: Dinner
            if (selectedWorkout.lowerBody == true)
            {
                // If there were categories set before
                if (lbl_categoryDifficulty.Text != "")
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = lbl_categoryDifficulty.Text + ", Unterkörper";
                }
                else
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = "AbendUnterkörperessen";
                }
            }

            // Category: Dessert
            if (selectedWorkout.fullBody == true)
            {
                // If there were categories set before
                if (lbl_categoryDifficulty.Text != "")
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = lbl_categoryDifficulty.Text + ", Oberkörper";
                }
                else
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = "Oberkörper";
                }
            }

            // Category: Snacks
            if (selectedWorkout.push == true)
            {
                // If there were categories set before
                if (lbl_categoryDifficulty.Text != "")
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = lbl_categoryDifficulty.Text + ", Push";
                }
                else
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = "Push";
                }
            }

            // Category: Drinks
            if (selectedWorkout.pull == true)
            {
                // If there were categories set before
                if (lbl_categoryDifficulty.Text != "")
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = lbl_categoryDifficulty.Text + ", Pull";
                }
                else
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = "Pull";
                }
            }

            // Category: Vegetarian
            if (selectedWorkout.twentyMinutes == true)
            {
                // If there were categories set before
                if (lbl_categoryDifficulty.Text != "")
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = lbl_categoryDifficulty.Text + ", 20 Minuten";
                }
                else
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = "20 Minuten";
                }
            }

            // Category: Vegan
            if (selectedWorkout.noEquipment == true)
            {
                // If there were categories set before
                if (lbl_categoryDifficulty.Text != "")
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = lbl_categoryDifficulty.Text + ", Ohne Geräte";
                }
                else
                {
                    // Set category text
                    lbl_categoryDifficulty.Text = "Ohne Geräte";
                }
            }


            //
            // Difficulties
            //

            // Difficulty beginner
            if (selectedWorkout.difficulty == "beginner")
            {
                // Set difficulty text
                lbl_categoryDifficulty.Text = lbl_categoryDifficulty.Text + ", Beginner";
            }

            // Difficulty advanced
            else if (selectedWorkout.difficulty == "advanced")
            {
                // Set difficulty text
                lbl_categoryDifficulty.Text = lbl_categoryDifficulty.Text + ", Fortgeschritten";
            }

            // Difficulty professional
            else if (selectedWorkout.difficulty == "hard")
            {
                // Set difficulty text
                lbl_categoryDifficulty.Text = lbl_categoryDifficulty.Text + ", Hart";
            }


            
            //
            // Recipe image
            //
            
            // Get recipe image from byte array
            var data = NSData.FromArray(selectedWorkout.WorkoutImage);

            // Convert to UIImage
            UIImage image = UIImage.LoadFromData(data);

            // Set as image
            imageView_Workout.Image = image;

            // AspectFill
            imageView_Workout.ContentMode = UIViewContentMode.ScaleAspectFill;
            
        }
    }
}
