// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace YeahFit
{
	public partial class UITableViewAddWorkoutExerciseCell : UITableViewCell
	{
		public UITableViewAddWorkoutExerciseCell (IntPtr handle) : base (handle)
		{
		}

        /// <summary>
        /// Update each cell content
        /// </summary>
        /// <param name="selectedStep"></param>
        /// <param name="indexPath"></param>
        /// <param name="tableView"></param>
        internal void UpdateCell(Exercise selectedExercise, int indexPath, UITableView tableView)
        {
            // Button for adding new steps
            btn_AddWorkoutExercise.TouchUpInside += (sender, e) =>
            {
                // Add new empty step
                AddWorkoutViewController.exercises.Add(new Exercise { ExerciseName = "" });
                
                // Reload tableView
                tableView.ReloadData();
            };
        }
    }
}
