// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace YeahFit
{
	public partial class UITableViewChallengeCell : UITableViewCell
	{
        bool liked;

        /// <summary>
        /// Custom cell in the FirtView for the individual recipes
        /// </summary>
        /// <param name="handle"></param>
        public UITableViewChallengeCell(IntPtr handle) : base(handle)
        {
        }

        /// <summary>
        /// Update each cell content
        /// </summary>
        /// <param name="selectedRecipe"></param>
        /// <param name="indexPath"></param>
        internal void UpdateCell(Challenge selectedChallenge, int indexPath)
        {
            // Set recipe text
            imageView_ChallengeOverview.Image = UIImage.GetSystemImage("heart.fill");
            lbl_ChallengeName.Text = selectedChallenge.RecipeName;
            lbl_ChallengeDaysPerWeek.Text = "";


            //
            // Categories
            //

            // Category: Breakfast
            if (selectedChallenge.breakfast == true)
            {
                // If there were categories set before
                if (lbl_ChallengeDaysPerWeek.Text != "")
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = lbl_ChallengeDaysPerWeek.Text + ", Frühstück";
                }
                else
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = "Frühstück";
                }
            }

            // Category: Lunch
            if (selectedChallenge.lunch == true)
            {
                // If there were categories set before
                if (lbl_ChallengeDaysPerWeek.Text != "")
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = lbl_ChallengeDaysPerWeek.Text + ", Mittagessen";
                }
                else
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = "Mittagessen";
                }
            }

            // Category: Dinner
            if (selectedChallenge.dinner == true)
            {
                // If there were categories set before
                if (lbl_ChallengeDaysPerWeek.Text != "")
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = lbl_ChallengeDaysPerWeek.Text + ", Abendessen";
                }
                else
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = "Abendessen";
                }
            }

            // Category: Dessert
            if (selectedChallenge.dessert == true)
            {
                // If there were categories set before
                if (lbl_ChallengeDaysPerWeek.Text != "")
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = lbl_ChallengeDaysPerWeek.Text + ", Dessert";
                }
                else
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = "Dessert";
                }
            }

            // Category: Snacks
            if (selectedChallenge.snacks == true)
            {
                // If there were categories set before
                if (lbl_ChallengeDaysPerWeek.Text != "")
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = lbl_ChallengeDaysPerWeek.Text + ", Snack";
                }
                else
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = "Snack";
                }
            }

            // Category: Drinks
            if (selectedChallenge.drinks == true)
            {
                // If there were categories set before
                if (lbl_ChallengeDaysPerWeek.Text != "")
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = lbl_ChallengeDaysPerWeek.Text + ", Getränk";
                }
                else
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = "Getränk";
                }
            }

            // Category: Vegetarian
            if (selectedChallenge.vegetarian == true)
            {
                // If there were categories set before
                if (lbl_ChallengeDaysPerWeek.Text != "")
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = lbl_ChallengeDaysPerWeek.Text + ", Vegetarisch";
                }
                else
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = "Vegetarisch";
                }
            }

            // Category: Vegan
            if (selectedChallenge.vegan == true)
            {
                // If there were categories set before
                if (lbl_ChallengeDaysPerWeek.Text != "")
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = lbl_ChallengeDaysPerWeek.Text + ", Vegan";
                }
                else
                {
                    // Set category text
                    lbl_ChallengeDaysPerWeek.Text = "Vegan";
                }
            }

            // If no category was selected
            if (
                selectedChallenge.breakfast == false &&
                selectedChallenge.lunch == false &&
                selectedChallenge.dinner == false &&
                selectedChallenge.dessert == false &&
                selectedChallenge.snacks == false &&
                selectedChallenge.vegetarian == false &&
                selectedChallenge.vegan == false &&
                selectedChallenge.drinks == false
                )
            // Set category text
            {
                lbl_ChallengeDaysPerWeek.Text = "Keine Kategorie ausgewählt";
            }


            //
            // Difficulties
            //

            // Difficulty beginner
            if (selectedChallenge.difficulty == "beginner")
            {
                // Set difficulty text
                lbl_ChallengeDaysPerWeek.Text = lbl_ChallengeDaysPerWeek.Text + ", Anfänger";
            }

            // Difficulty advanced
            else if (selectedChallenge.difficulty == "advanced")
            {
                // Set difficulty text
                lbl_ChallengeDaysPerWeek.Text = lbl_ChallengeDaysPerWeek.Text + ", Fortgeschritten";
            }

            // Difficulty professional
            else if (selectedChallenge.difficulty == "professional")
            {
                // Set difficulty text
                lbl_ChallengeDaysPerWeek.Text = lbl_ChallengeDaysPerWeek.Text + ", Profi";
            }


            //
            // Liked
            //

            // Set liked
            liked = selectedChallenge.liked;
            if (liked == false)
            {
                liked = false;

                // Set image View with the normal heart
                imageView_LikeChallenge.Image = UIImage.GetSystemImage("heart");
            }
            else if (liked == true)
            {
                // Set image View with the filled heart
                imageView_LikeChallenge.Image = UIImage.GetSystemImage("heart.fill");
            }


            //
            // Recipe image
            //

            // Get recipe image from byte array
            var data = NSData.FromArray(selectedChallenge.RecipeImage);

            // Convert to UIImage
            UIImage image = UIImage.LoadFromData(data);

            // Set as image
            imageView_ChallengeOverview.Image = image;

            // AspectFill
            imageView_ChallengeOverview.ContentMode = UIViewContentMode.ScaleAspectFill;

        }
    }
}
