// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace YeahFit
{
    public partial class UITableViewWorkoutCell : UITableViewCell
    {
            bool liked;

            /// <summary>
            /// Custom cell in the FirtView for the individual recipes
            /// </summary>
            /// <param name="handle"></param>
            public UITableViewWorkoutCell (IntPtr handle) : base(handle)
            {
            }
            
            /// <summary>
            /// Update each cell content
            /// </summary>
            /// <param name="selectedRecipe"></param>
            /// <param name="indexPath"></param>
            internal void UpdateCell(Workout selectedWorkout, int indexPath)
            {
                // Set recipe text
                imageView_LikeWorkout.Image = UIImage.GetSystemImage("heart.fill");
                lbl_WorkoutName.Text = selectedWorkout.WorkoutName;
                lbl_WorkoutCategory.Text = "";


                
                // Category: Breakfast
                if (selectedWorkout.core == true)
                {
                    // If there were categories set before
                    if (lbl_WorkoutCategory.Text != "")
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = lbl_WorkoutCategory.Text + ", Core";
                    }
                    else
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = "Core";
                    }
                }

                // Category: Lunch
                if (selectedWorkout.upperBody == true)
                {
                    // If there were categories set before
                    if (lbl_WorkoutCategory.Text != "")
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = lbl_WorkoutCategory.Text + ", Oberkörper";
                    }
                    else
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = "Oberkörper";
                    }
                }

                // Category: Dinner
                if (selectedWorkout.lowerBody == true)
                {
                    // If there were categories set before
                    if (lbl_WorkoutCategory.Text != "")
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = lbl_WorkoutCategory.Text + ", Unterkörper";
                    }
                    else
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = "Unterkörper";
                    }
                }

                // Category: Dessert
                if (selectedWorkout.fullBody == true)
                {
                    // If there were categories set before
                    if (lbl_WorkoutCategory.Text != "")
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = lbl_WorkoutCategory.Text + ", Ganzkörper";
                    }
                    else
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = "Ganzkörper";
                    }
                }

                // Category: Snacks
                if (selectedWorkout.push == true)
                {
                    // If there were categories set before
                    if (lbl_WorkoutCategory.Text != "")
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = lbl_WorkoutCategory.Text + ", Push";
                    }
                    else
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = "Push";
                    }
                }

                // Category: Drinks
                if (selectedWorkout.pull == true)
                {
                    // If there were categories set before
                    if (lbl_WorkoutCategory.Text != "")
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = lbl_WorkoutCategory.Text + ", Pull";
                    }
                    else
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = "Pull";
                    }
                }

                // Category: Vegetarian
                if (selectedWorkout.twentyMinutes == true)
                {
                    // If there were categories set before
                    if (lbl_WorkoutCategory.Text != "")
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = lbl_WorkoutCategory.Text + ", 20 Minuten";
                    }
                    else
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = "20 Minuten";
                    }
                }

                // Category: Vegan
                if (selectedWorkout.noEquipment == true)
                {
                    // If there were categories set before
                    if (lbl_WorkoutCategory.Text != "")
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = lbl_WorkoutCategory.Text + ", Ohne Geräte";
                    }
                    else
                    {
                        // Set category text
                        lbl_WorkoutCategory.Text = "Ohne Geräte";
                    }
                }

                //
                // Difficulties
                //

                // Difficulty beginner
                if (selectedWorkout.difficulty == "Beginner")
                {
                    // Set difficulty text
                    lbl_difficulty.Text = "Beginner";
                }

                // Difficulty advanced
                else if (selectedWorkout.difficulty == "Fortgeschritten")
                {
                    // Set difficulty text
                    lbl_difficulty.Text = "Fortgeschritten";
                }

                // Difficulty professional
                else if (selectedWorkout.difficulty == "Hart")
                {
                    // Set difficulty text
                    lbl_difficulty.Text = "Hart";
                }


                //
                // Duration
                //

                // Convert duration from int (seconds)  to TimeSpan
                TimeSpan duration = TimeSpan.FromSeconds(selectedWorkout.duration);

                // Set Duration as string
                lbl_duration.Text = duration.ToString(@"hh\:mm");


                //
                // Liked
                //

                // Set liked
                liked = selectedWorkout.liked;
                if (liked == false)
                {
                    liked = false;

                    // Set image View with the normal heart
                    imageView_LikeWorkout.Image = UIImage.GetSystemImage("heart");
                }
                else if (liked == true)
                {
                    // Set image View with the filled heart
                    imageView_LikeWorkout.Image = UIImage.GetSystemImage("heart.fill");
                }


                //
                // Recipe image
                //

                // Get recipe image from byte array
                var data = NSData.FromArray(selectedWorkout.WorkoutImage);

                // Convert to UIImage
                UIImage image = UIImage.LoadFromData(data);

                // Set as image
                imageView_Workout.Image = image;

                // AspectFill
                imageView_Workout.ContentMode = UIViewContentMode.ScaleAspectFill;
                
            }
        }
    }