// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace YeahFit
{
    public partial class UITableViewLastWorkoutCell : UITableViewCell
    {
        List<LastWorkout> lastWorkout = new List<LastWorkout>();

        public UITableViewLastWorkoutCell(IntPtr handle) : base(handle)
        {
        }

        /// <summary>
        /// Update each cell content
        /// </summary>
        /// <param name="selectedIngredient"></param>
        /// <param name="indexPath"></param>
        internal void UpdateCell(Workout selectedWorkout, int indexPath)
        {
            lastWorkout = InitializeLastWorkouts.LastWorkout;

            for(int i = 0; i < lastWorkout.Count; i++)
            {
                if (selectedWorkout.id == lastWorkout[i].WorkoutID)
                {
                    lbl_WorkoutDate.Text = (lastWorkout[i].WorkoutDateTime).ToString();
                }
            }

            // Set ingredient text
            lbl_WorkoutName.Text = selectedWorkout.WorkoutName;

            //
            // Recipe image
            //

            // Get recipe image from byte array
            var data = NSData.FromArray(selectedWorkout.WorkoutImage);

            // Convert to UIImage
            UIImage image = UIImage.LoadFromData(data);

            // Set as image
            imageView_Workout.Image = image;

            // AspectFill
            imageView_Workout.ContentMode = UIViewContentMode.ScaleAspectFill;
        }
    }
}
