// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace YeahFit
{
	public partial class WeekTableView : UITableView
	{
		public WeekTableView (IntPtr handle) : base (handle)
		{
		}
	}
}
