// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace YeahFit
{
    public partial class WeekSettingsViewController : UIViewController
    {
        public static FirstViewController firstViewController;

        bool internalMonday = false;
        bool internalTuesday = false;
        bool internalWednesday = false;
        bool internalThursday = false;
        bool internalFriday = false;
        bool internalSaturday = false;
        bool internalSunday = false;

        public WeekSettingsViewController(IntPtr handle) : base(handle)
        {
        }

        /// <summary>
        /// Initialize
        /// </summary>
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            internalMonday = InitializeWeek.monday;
            internalTuesday = InitializeWeek.tuesday;
            internalWednesday = InitializeWeek.wednesday;
            internalThursday = InitializeWeek.thursday;
            internalFriday = InitializeWeek.friday;
            internalSaturday = InitializeWeek.saturday;
            internalSunday = InitializeWeek.sunday;

            btn_Monday.TouchUpInside += (sender, e) =>
            {
                if (internalMonday == true)
                {
                    SelectButtonColor.SelectButton(btn_Monday, false);
                    internalMonday = false;
                }
                else
                {
                    SelectButtonColor.SelectButton(btn_Monday, true);
                    internalMonday = true;
                }
            };
            btn_Tuesday.TouchUpInside += (sender, e) =>
            {

            };
            btn_Wednesday.TouchUpInside += (sender, e) =>
            {

            };
            btn_Thursday.TouchUpInside += (sender, e) =>
            {

            };
            btn_Friday.TouchUpInside += (sender, e) =>
            {

            };
            btn_Saturday.TouchUpInside += (sender, e) =>
            {

            };
            btn_Sunday.TouchUpInside += (sender, e) =>
            {

            };
            btn_SaveWeek.TouchUpInside += (sender, e) =>
            {
                if (LoginViewController.loggedin == true)
                {

                    this.DismissViewController(true, () => { FirstViewController.Refresh(firstViewController); });
                }
                else
                {
                    //Create Alert
                    var okAlertController = UIAlertController.Create("Melde dich an", "Melde dich an, um deine Woche einzustellen.", UIAlertControllerStyle.Alert);

                    //Add Action
                    okAlertController.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));

                    // Present Alert
                    PresentViewController(okAlertController, true, null);
                }
            };
        }

        /// <summary>
        /// Reload FirstView if user swipes down the View
        /// + Set edit in SecondView false
        /// </summary>
        /// <param name="animated"></param>
        public override void ViewDidDisappear(bool animated)
        {
            base.ViewDidDisappear(animated);


        }
    }
}
