// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace YeahFit
{
	public partial class WorkoutStepViewController : UIViewController
	{
        public static int index;
        public static Workout selectedWorkout;


        NSTimer timer;
        int seconds = 0;

        public WorkoutStepViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            lbl_ExerciseName.Text = selectedWorkout.Exercises[index].IngredientName;
            lbl_SetsReps.Text = selectedWorkout.Exercises[index].IngredientAmount;
            if (selectedWorkout.Exercises[index + 1] != null)
            {
                lbl_NextExercise.Text = "Nächste Übung: " + selectedWorkout.Exercises[index + 1].IngredientName;
            }
            else
            {
                lbl_NextExercise.Text = "Letzte Übung";
            }

            timer = NSTimer.CreateRepeatingScheduledTimer(TimeSpan.FromSeconds(1), delegate
            {
                seconds++;
                int minutes = seconds / 60;
                int remainingSeconds = seconds % 60;
                timerLabel.Text = $"{minutes}:{remainingSeconds:00}";
            });
        }

        public override void ViewWillDisappear(bool animated)
        {
            base.ViewWillDisappear(animated);
            timer.Invalidate();
        }

        void ResetTimer()
        {
            seconds = 0;
            timerLabel.Text = "0:00";
        }
    }
}
