// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using MySql.Data.MySqlClient;
using UIKit;
using System.Drawing;

namespace YeahFit
{
	public partial class WorkoutOverviewViewController : UIViewController
	{
        public UINavigationController CurrentNavigationController;

        // Main list of all recipes
        public static List<Workout> workouts;


        public WorkoutOverviewViewController(IntPtr handle) : base(handle)
        {
        }


        /// <summary>
        /// Initialization of the main view 'FirstView'
        /// </summary>
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            // Perform any additional setup after loading the view, typically from a nib.

            // Buttons for setting categories
            btn_FullBody.TouchUpInside += (sender, e) =>
            {
                if (InitializeWorkouts.category == "fullBody")
                {
                    InitializeWorkouts.category = "";
                }
                else
                {
                    InitializeWorkouts.category = "fullBody";
                }
                ViewDidAppear(true);
            };
            btn_UpperBody.TouchUpInside += (sender, e) =>
            {
                if (InitializeWorkouts.category == "upperBody")
                {
                    InitializeWorkouts.category = "";
                }
                else
                {
                    InitializeWorkouts.category = "upperBody";
                }
                ViewDidAppear(true);
            };
            btn_LowerBody.TouchUpInside += (sender, e) =>
            {
                if (InitializeWorkouts.category == "lowerBody")
                {
                    InitializeWorkouts.category = "";
                }
                else
                {
                    InitializeWorkouts.category = "lowerBody";
                }
                ViewDidAppear(true);
            };
            btn_Push.TouchUpInside += (sender, e) =>
            {
                if (InitializeWorkouts.category == "push")
                {
                    InitializeWorkouts.category = "";
                }
                else
                {
                    InitializeWorkouts.category = "push";
                }
                ViewDidAppear(true);
            };
            btn_Pull.TouchUpInside += (sender, e) =>
            {
                if (InitializeWorkouts.category == "pull")
                {
                    InitializeWorkouts.category = "";
                }
                else
                {
                    InitializeWorkouts.category = "pull";
                }
                ViewDidAppear(true);
            };
            btn_Core.TouchUpInside += (sender, e) =>
            {
                if (InitializeWorkouts.category == "core")
                {
                    InitializeWorkouts.category = "";
                }
                else
                {
                    InitializeWorkouts.category = "core";
                }
                ViewDidAppear(true);
            };
            btn_TwentyMinutes.TouchUpInside += (sender, e) =>
            {
                if (InitializeWorkouts.category == "twentyMinutes")
                {
                    InitializeWorkouts.category = "";
                }
                else
                {
                    InitializeWorkouts.category = "twentyMinutes";
                }
                ViewDidAppear(true);
            };
            btn_NoEquipment.TouchUpInside += (sender, e) =>
            {
                if (InitializeWorkouts.category == "noEquipment")
                {
                    InitializeWorkouts.category = "";
                }
                else
                {
                    InitializeWorkouts.category = "noEquipment";
                }
                ViewDidAppear(true);
            };
            


            // Loading the tableView
            FilterViewController.workoutOverviewViewController = this;
            WorkoutViewController.firstViewController = this;
            workouts = null;
            WorkoutViewController.lastWorkouts = false;
            WorkoutViewController.challenge = false;

            // Get data from database
            InitializeWorkouts.Initialize();

            // Setting recipes as its source
            tableView_Workouts.Source = new WorkoutTableViewSource(workouts, this, CurrentNavigationController);
            tableView_Workouts.RowHeight = 360;

            // Reload tableView
            tableView_Workouts.ReloadData();

        }

        /// <summary>
        /// Reload tabeView_Recipes after view reappeared
        /// </summary>
        /// <param name="animated"></param>
        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);
            FilterViewController.workoutOverviewViewController = this;
            WorkoutViewController.lastWorkouts = false;
            WorkoutViewController.challenge = false;
            WorkoutViewController.firstViewController = this;
            workouts = null;
            InitializeWorkouts.Initialize();
            tableView_Workouts.Source = new WorkoutTableViewSource(workouts, this, CurrentNavigationController);
            tableView_Workouts.RowHeight = 360;
            tableView_Workouts.ReloadData();
        }

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();
            // Release any cached data, images, etc that aren't in use.
        }

        public override void ViewDidDisappear(bool animated)
        {
            base.ViewDidDisappear(animated);
            this.DismissViewController(true, () => { FilterViewController.workoutOverviewViewController = this; });
        }

        /// <summary>
        /// Reload tabeView_Recipes from other Views
        /// </summary>
        /// <param name="firstViewController"></param>
        public static void Refresh(WorkoutOverviewViewController firstViewController)
        {
            firstViewController.ViewDidAppear(true);
        }
    }
}
