// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;
using Foundation;
using UIKit;

namespace YeahFit
{
	public partial class YeahFitTabBarController : UITabBarController
	{
		public YeahFitTabBarController (IntPtr handle) : base (handle)
		{
        }
	}
}
